### ISSUE TITLE
Status of this repo?

### ISSUE THREAD

**Issue by shaneparsons** [VROOM-Project/vroom-docker#1]
I just stumbled upon VROOM the other day, so I haven't been here long enough to know the plans. Is a docker image / implementation planned for the near future? Is there an example of a current docker implementation elsewhere?

**Comment by jcoupey** [comment]
Following the discussion at https://github.com/VROOM-Project/vroom/issues/307, we plan to publish "official" Docker images for `vroom` and `vroom-express`.

This (still empty) repo has just been created for that purpose and is where it should happen.

In the meantime, there are other docker work available, e.g. at https://github.com/iedmrc/vroom-docker.

**Comment by jcoupey** [comment]
Closing as this is now made clear in the readme.
