### ISSUE TITLE
example of config files

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom-docker#11]
I think it is useful to insert some sample files in this project in a directory **./conf/** already inserted.
it's a good idea?

**Comment by jcoupey** [comment]
Can you expand on what config file you have in mind: is it the `vroom-express` yaml config or something related to Docker or the `docker-compose.yml` file?

**Comment by stefanocudini** [comment]
yes I'm sorry for my carelessness

I mean the config directory mounted as volume:
`-v $PWD/conf:/conf`

**Comment by nilsnolde** [comment]
Please consult the README first. Where it states:
`All relevant files are located inside the container's /conf directory and can be shared with the host.`

If you'd actually run the example command, you'd realize that `./conf` is going to be created **on your machine**, which contains the config.yml for you to tweak as you wish.

**Comment by stefanocudini** [comment]
thankyou @nilsnolde
