### ISSUE TITLE
Unable to run docker compose on mac

### ISSUE THREAD

**Issue by jfalameda** [VROOM-Project/vroom-docker#12]
Hi,

I cannot manage to run the server on mac. I do get the following error:

`ERROR: for ors  Cannot start service ors: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/josefa/projects/vroom-docker-master/data/heidelberg.osm.gz\\\" to rootfs \\\"/var/lib/docker/overlay2/3eda84bd2d4f9e7b9b2c63c48866d28c40d9b2644b3c78d5436dfec2abb802fb/merged\\\" at \\\"/var/lib/docker/overlay2/3eda84bd2d4f9e7b9b2c63c48866d28c40d9b2644b3c78d5436dfec2abb802fb/merged/ors-core/data/osm_file.pbf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

Thanks,
José.

**Comment by thiagotalma** [comment]
@jfalameda Were you able to solve the problem?

**Comment by tk6ix9ine** [comment]
hi @jfalameda, How did you solve this problem?
