### ISSUE TITLE
Adjust dependencies

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom-docker#15]
Some adjustments are required in order to build an image against the next `v1.7.0` release of VROOM, see https://github.com/VROOM-Project/vroom/blob/release/1.7/CHANGELOG.md for details.

It basically comes down to dropping all `boost` dependencies and adding `asio` as a standalone dependency (`libasio-dev` package).

Hopefully this will result in a decreased size for the image, would be interesting to measure the difference.

**Comment by nilsnolde** [comment]
Sorry, I somehow forgot about this. With 1.7.0 release out now, I'll take care of it this week.

**Comment by jcoupey** [comment]
Ah ah @nilsnolde fast as a bot on that one. ;-) 

No problem, it's great if this happens in the next few days.
