### ISSUE TITLE
access.log not accessible from host

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom-docker#2]
Did some stupid stuff in `docker-entrypoint.sh`..

Will have to implement smth that prohibits a Docker user to change location of the `logdir` config variable (alternatively, we could employ another env var, but I think it should be fair enough this way).

**Comment by nilsnolde** [comment]
Hm, actually we can't expose the `access.log` file right now at all, no matter what I do. For `config.yml` we have a "hack" where I copy the actual config from the repo to a shared directory (and back again). For `access.log` that doesn't work, as it's well.. a log. 

So, I only see the option to hard-code the log file path to the shared directory in the image and then set the file path appropriately in `vroom-express`. @jcoupey, that'd mean the `access.log` file path would need to be settable via environment variable as well in `vroom-express`. You're ok with that?

**Comment by jcoupey** [comment]
> the access.log file path would need to be settable via environment variable as well in vroom-express

OK for me.

As soon as we've done all required additions at the `vroom-express` level, I suggest we release a v0.5.1 patch version for compatibility before the first release on this repo.
