### ISSUE TITLE
Build rc version image 

### ISSUE THREAD

**Issue by braktar** [VROOM-Project/vroom-docker#20]
@jcoupey has tagged a release candidate version v1.8.0-rc.1

We are actually [using the image available on dockerhub](https://github.com/braktar/optimizer-api/blob/87c1608ab14ed7911bf0a23630e0e8bb06434bd8/docker/Dockerfile#L10) within our test and deployment process.

As I want to test this version, which contains some interesting fixes, I do not want to change the build process for this specific moment between a RC and a proposer release.

@nilsnolde what do you think about it ?

**Comment by nilsnolde** [comment]
IMO nothing speaks against building and tagging the v1.8.0-rc.1 image. If @jcoupey is fine with that too, I'd just like to know if anything changed in the build process? I guess not from the more recent commits I've seen. In that case, I can do it sometime the next two days as it's really a quick one.

**Comment by jcoupey** [comment]
Well the purpose of release candidates are to allow some more testing before a stable release, so if pushing a docker image helps in that prospect I'm all for it.

@nilsnolde maybe we can include RC versions as part of the `vroom-docker` workflow as a general rule? Nothing has changed wrt building so this is more or less the same as the last release you pushed on Docker Hub.

**Comment by nilsnolde** [comment]
> maybe we can include RC versions as part of the vroom-docker workflow as a general rule?

Sure. I just extended the Dockerhub build rule to pick up any tag basically. Just hit me whenever you're doing RC and I'll tag it here.

The image is building on Dockerhub right now:)
