### ISSUE TITLE
Cannot run the docker using docker-compose up -d

### ISSUE THREAD

**Issue by ziaadilh** [VROOM-Project/vroom-docker#22]
ERROR: for ors  Cannot start service ors: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/synergy/Documents/vroom-docker/data/heidelberg.osm.gz\\\" to rootfs \\\"/var/lib/docker/overlay2/16d6dd375f56cfbd9f7b8295edadf6a004dccf8e459019cd051038199712768f/merged\\\" at \\\"/var/lib/docker/overlay2/16d6dd375f56cfbd9f7b8295edadf6a004dccf8e459019cd051038199712768f/merged/ors-core/data/osm_file.pbf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by nilsnolde** [comment]
Can you pls paste your full `docker-compose.yml`?

**Comment by nilsnolde** [comment]
And also a `tree -L 4 /home/synergy/Documents/vroom-docker/` pls

**Comment by ziaadilh** [comment]
version: "2.4"
services:
  vroom:
    network_mode: host
    image: vroomvrp/vroom-docker:v1.8.0
    container_name: vroom
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=ors  # router to use, osrm or ors
    depends_on:
      - ors
  # Example for OpenRouteService
  ors:
    container_name: ors
    ports:
      - 8080:8080
    image: openrouteservice/openrouteservice:latest
    volumes:
      - ./graphs:/ors-core/data/graphs
      - ./elevation_cache:/ors-core/data/elevation_cache
      - ./logs/ors:/var/log/ors
      - ./logs/tomcat:/usr/local/tomcat/logs
      - ./conf:/ors-conf
      - ./data/heidelberg.osm.gz:/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed in app.config
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
  # Example for OSRM
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./osrm:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/map.osrm"

**Comment by ziaadilh** [comment]
├── CHANGELOG.md
├── conf
├── data
│   └── heidelberg.osm.gz
├── docker-compose.yml
├── docker-entrypoint.sh
├── Dockerfile
├── elevation_cache
├── graphs
├── LICENSE
├── logs
│   ├── ors
│   └── tomcat
├── osrm
└── README.md

**Comment by nilsnolde** [comment]
yeah, there's definitely smth wrong with the default docker-compose in this repo. do note that you should choose **one** routing provider, either OSRM **or** ORS. That's not the source of the problem here, but with your settings you'd start both routing engines, but you'd only use ORS with vroom (`VROOM_ROUTER` env variable in the `vroom` service). I'll get back to you soon. Seems that smth will need to be fixed in the ORS image itself. Rather annoying.. ;)

**Comment by ziaadilh** [comment]
But as per docker-compose.yml file there is only service is using 
environment:
      - VROOM_ROUTER=ors

**Comment by nilsnolde** [comment]
there were 2 issues here:
- the docker-compose was not properly set up: you need to specify your own OSM PBF file
- also ORS changed to java 11 (from 8) and there was a deprecated java option specified

I fixed those issues, so you can update and it should just run. 

> But as per docker-compose.yml file there is only service is using

Sure, that's my point. It's (vroom-express) is only ever using one routing engine. Though there might actually be instances where you'd like to run 2 different routing engines depending on the specific use case, the project is not (yet) able to do that. In your case, it seems you'd like to use ORS, so you don't have to start an OSRM instance, it's wasted memory. BTW, OSRM also seems to have problems, see #21, but easy to work around.

**Comment by tk6ix9ine** [comment]
the same problem here with the latest version of docker-compose.yml :(
