### ISSUE TITLE
OSRM Backend Image issue

### ISSUE THREAD

**Issue by ziaadilh** [VROOM-Project/vroom-docker#23]
New issue is that orsm-data images name is incorrect. 

Pulling osrm (osrm-data/osrm-backend:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

The image name should be osrm/osrm-backend

**Comment by nilsnolde** [comment]
Jep, will be solved with #21
