### ISSUE TITLE
osrm exited with code 1

### ISSUE THREAD

**Issue by itsazzad** [VROOM-Project/vroom-docker#28]
Is that normal?
> Creating network "vroom-docker_default" with the default driver
> --
> Creating osrm ... done
> Creating vroom ... done
> Attaching to osrm, vroom
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.ramIndex
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.fileIndex
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.edges
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.geometry
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.turn_weight_penalties
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.turn_duration_penalties
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.datasource_names
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.names
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.timestamp
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.properties
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.icd
> osrm  \| [warn] Missing/Broken File: /data/map.osrm.maneuver_overrides
> osrm  \| [error] Required files are missing, cannot continue
> osrm exited with code 1
> vroom \|
> vroom \| > vroom-express@0.7.0 start /vroom-express
> vroom \| > node src/index.js
> vroom \| vroom-express listening on port 3000!

**Comment by nilsnolde** [comment]
You'll need to have graphs built with OSRM before you can use the default docker-compose.yml, which is simply an example usage, with OSRM. Refer to its docker repository: https://hub.docker.com/r/osrm/osrm-backend/
