### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom-docker#34]
The [readme](https://github.com/VROOM-Project/vroom-docker#tagging) states that:

> The tagging scheme follows the release convention of vroom and adds patch releases for vroom-express patch releases.

This may be a bit confusing, and also problematic. Suppose we tag a `v1.9.1` here for the sake of a new `vroom-express` release, but then have to patch `v1.9.0` to `v1.9.1` in the core repo? This never actually happened but we should avoid the ambiguity.

What about simply using the `vroom` version as that's the most important part (not much changes on the `vroom-express` side). Then implicitly the `vroom-express` version would be the latest available when pushing the image. That would work smoothly because we usually sync releases.

**Comment by nilsnolde** [comment]
Sure, it all depends on your release scheme for those two;) I thought it'd be nicer to pin vroom-express to a version for a vroom-docker version, but I do agree, it can add ambiguity in case of vroom core patches. Always using the newest master of vroom-express for a new vroom-docker release could also be ambiguous: we tag 1.10.0 here, then `vroom-express` gets an unrelated (to core) and important update with 0.9.0 or so; we'd have to wait until a new vroom release is made or you'd have to release a patch vroom version only to satisfy vroom-docker?

How about ditching semantic versioning instead and tag both repo versions, e.g. `v1.9.0-v0.8.0`, going forward?

**Comment by jcoupey** [comment]
My point is that the most important changes are on the `vroom` side. We don't have that many "important updates" for `vroom-express`. And they never wait for too long since core versions are released quite frequently.

**Comment by nilsnolde** [comment]
Ok, I don't care _too_ much: I'll be in-sync with vroom core then and change the tagging description.

**Comment by jcoupey** [comment]
This has been documented in the readme with #36.
