### ISSUE TITLE
vroom docker not responding to  request with large custom matrix

### ISSUE THREAD

**Issue by ibrahimsk1** [VROOM-Project/vroom-docker#38]
vroom docker works when i send a 5 job request with custom matrix but when i send 250 jobs with custom matrix then i dont get respond.when i try with postman for small request i get succesful response and for large one i get socket hang up error. I changed request timeout to  never timeout. I guess problem is custom matrix because for 250 jobs its about 62.500 lines. How can i solve this problem ?Does anyone have an idea? Thanks

**Comment by nilsnolde** [comment]
thanks for the good analysis @ibrahimsk1 ! I'll try to reproduce soon, maybe I can find out what the problem is. 

> find that maximum 150kb json is accepted

good hint

**Comment by ibrahimsk1** [comment]
@jcoupey  @nilsnolde  Thanks for your answers.

Actually to find solution i deleted docker image and installed vroom and vroom express seperatly.After that i tried same requests and got same responses. I guess the problem is in vroom express.

**Comment by nilsnolde** [comment]
What you'll need to adjust here is the `limit` parameter for `vroom-express`: https://github.com/VROOM-Project/vroom-express/blob/master/config.yml#L6

Default is 1 MB, your file is 1.6 MB. But really strange that it's not giving _some_ sort of sane error.. You can close if that fixed it for you as well.

**Comment by ibrahimsk1** [comment]
Yes changing size limit worked for me. Thanks @nilsnolde .
