### ISSUE TITLE
Need help how to use this

### ISSUE THREAD

**Issue by DeDeQue** [VROOM-Project/vroom-docker#39]
Hi all,

I need to have: 
OpenRouteService -> Vroom -> Vroom Express
running on my self hosted AWS Server so I can call the Rest API for commands specified here:
https://github.com/VROOM-Project/vroom/blob/master/docs/API.md

I have good programming experience in C# but I never worked with servers at all. I am struggling to get anything started for days now and in the description, it says something about 3 minutes, which seems embarrasing.

I even tried to find help over freelancer.com but all applicants turned out to be scammers who tried to get my AWS main credentials. 

I watched this Tutorial about deploying docker containers in AWS EC2 (https://www.youtube.com/watch?v=lO2wU2rcGUw&ab_channel=CloudSkills) but when typing: 

docker pull vroomvrp/vroom-docker

I already get the error: manifest for vroomvrp/vroom-docker: latest not found.

I would appreciate any help, hint or consultation offer!

**Comment by nilsnolde** [comment]
Sure, you can write me on enquiry at gis-ops dot com, we can get you sorted.
