### ISSUE TITLE
Installed but getting an error

### ISSUE THREAD

**Issue by kevin8181** [VROOM-Project/vroom-docker#40]
I have installed this and got it running, got code 200 back when running the health test. When I try to run the example command I get the response
`{"code":3,"error":"Failed to connect to 0.0.0.0:5000"}`

What am I doing wrong?

**Comment by nilsnolde** [comment]
Can only say when I know what you actually did;) (docker-compose.yml and the command(s) you used to start docker)

**Comment by kevin8181** [comment]
this command from the readme

`docker run -dt --name vroom \
    --net host \  # or set the container name as host in config.yml and use --port 3000:3000 instead, see below
    -v $PWD/conf:/conf \ # mapped volume for config & log
    -e VROOM_ROUTER=osrm \ # routing layer: osrm, valhalla or ors
    vroomvrp/vroom-docker:v1.10.0
`

and then 'sudo docker start <container id>`

**Comment by nilsnolde** [comment]
You're missing the routing engine then. A few lines further down it says 
> Note, you should have access to a self-hosted instance of OSRM, Valhalla or OpenRouteService for the routing server, see e.g. docker-compose.yml for an example.

Read through it again, should be self-explanatory if you know docker a bit.

**Comment by myrondeliverone** [comment]
Reading the instruction this would only address my problem if I was building the image myself. I was not. I took that everything after "If you want to build the image yourself, run a" to only apply to when you are building it.  That is why I posted my question because this answer was for another path.
