### ISSUE TITLE
{"code":3,"error":"Failed to connect to 0.0.0.0:5000"}

### ISSUE THREAD

**Issue by myrondeliverone** [VROOM-Project/vroom-docker#43]
I am not trying to build a new image but just run the one you guys created.
I am running Docker Desktop for Windows.
I ran this command:
docker run -dt --name vroom  --net host -v /vroom-vol -e VROOM_ROUTER=osrm vroomvrp/vroom-docker:v1.10.0
Got this feedback from the command:
Unable to find image 'vroomvrp/vroom-docker:v1.10.0' locally
v1.10.0: Pulling from vroomvrp/vroom-docker
f7ec5a41d630: Pull complete
af85e22911d9: Pull complete
07060573ed70: Pull complete
a082ae6404c8: Pull complete
0aa4da5b6a9b: Pull complete
e6800109a6e6: Pull complete
17b951da241f: Pull complete
126790e7b93b: Pull complete
3a78032756fb: Pull complete
Digest: sha256:c2971c02a5c2f2e4b1c8507bde40db4a0f305c1a2fefaec8a0db02e76e01a53b
Status: Downloaded newer image for vroomvrp/vroom-docker:v1.10.0
016aeb22cfbc20a42f1c0ba828f62228a3f02ea7e5f2e8aef8c5f18e87db514d

Then tried to post to the images and got this in the log:
{"code":3,"error":"Failed to connect to 0.0.0.0:5000"}

I have been beating my head against the wall on this problem for the last 10 hours. Please someone help. This is the first time I have ever used Docker

**Comment by nilsnolde** [comment]
see #40 for a solution
