### ISSUE TITLE
Update to VROOM 1.11.0

### ISSUE THREAD

**Issue by mhosman** [VROOM-Project/vroom-docker#46]
Hey guys, can we update this to the last VROOM version? Thank you so much!

**Comment by jcoupey** [comment]
Ah, that was fast. ;-)

@nilsnolde I've tagged `v0.10.0` on `vroom-express` in order to include the latest dependency updates you've made there in the next image.

**Comment by nilsnolde** [comment]
https://hub.docker.com/layers/vroomvrp/vroom-docker/v1.11.0/images/sha256-3dfaca36d2870ff2ec19abc77c4843393362227dda990f2e01240995589663e0?context=repo
