### ISSUE TITLE
new timeout flag (-l) seems not working in vroom-docker

### ISSUE THREAD

**Issue by CosmoVal** [VROOM-Project/vroom-docker#48]
Hi, 

I'm using vroom-docker and the CLI flags `c, g, x, t` are working fine for me, meaning they are actually processed correctly and I get coherent results. 

However, when I pass the new arg `-l` for the timeout, it seems it's not taken into account: the responses seem to ignore this parameter and the runtime it's exactly the one I obtain when that flag it's not passed at all.

My question: is the timeout flag `-l` expected to work also in the docker architecture?

**Comment by nilsnolde** [comment]
Indeed, it's released in the appropriate vroom release: https://github.com/VROOM-Project/vroom/blob/master/CHANGELOG.md#added-1

but in the vroom-express release: https://github.com/VROOM-Project/vroom-express/blob/master/CHANGELOG.md#unreleased

should we cut one @jcoupey ?

**Comment by jcoupey** [comment]
Support for `-l` has indeed been added to vroom-express after the last vroom-docker update, see https://github.com/VROOM-Project/vroom-express/pull/91.

So this will be included in the next vroom-docker release when we point to a new vroom-express version. Note that using `vroom -l` without going through vroom-express should work right now.

**Comment by CosmoVal** [comment]
Great, thanks for the quick answer. 

Do you know, more or less, when the next vroom-docker release will be?

**Comment by jcoupey** [comment]
More or less in the next few months...
