### ISSUE TITLE
Unable to run localhost:3000/health

### ISSUE THREAD

**Issue by duongnv1989** [VROOM-Project/vroom-docker#49]
Hi.
I use `docker-compose.yml` to run, however when I check http://localhost:3000/health it says not working.
Here is the content of my `docker-compose.yml` file:
[docker-compose.txt](https://github.com/VROOM-Project/vroom-docker/files/8723362/docker-compose.txt)
Hope to get help soon. Thanks.

**Comment by nilsnolde** [comment]
sorry, that's windows, no idea

**Comment by duongnv1989** [comment]
Thanks for the feedback, I found the solution https://github.com/VROOM-Project/vroom-docker/issues/44
