### ISSUE TITLE
Endpoints of the vroom docker image for optimization??

### ISSUE THREAD

**Issue by MohithReddy1** [VROOM-Project/vroom-docker#54]
What is the endpoint of the vroom docker image for optimization for multiple points routing?

**Comment by MohithReddy1** [comment]
For the docker image, I am integrating with ORS, and the status for http://localhost:3000/health is Error and Connection was refused by the server. 

My docker-compose.yml file 

version: "2.4"
services:
  vroom:
    network_mode: host
    image: vroomvrp/vroom-docker:v1.9.0
    container_name: vroom
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=ors  # router to use, osrm, valhalla or ors
    depends_on:
      - ors

ors:
    container_name: ors
    ports:
      - 8080:8080
    image: openrouteservice/openrouteservice:latest
    volumes:
      - ./graphs:/ors-core/data/graphs
      - ./elevation_cache:/ors-core/data/elevation_cache
      - ./logs/ors:/var/log/ors
      - ./logs/tomcat:/usr/local/tomcat/logs
      - ./conf:/ors-conf
      - ./your_osm.pbf:/ors-core/data/osm_file.pbf  # alter path to your local OSM PBF file, e.g. from https://download.geofabrik.de
    environment:
      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed in app.config
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"

**Comment by nilsnolde** [comment]
what's the output of the ors docker logs? you don't build any graph with that config: `./your_osm.pbf:/ors-core/data/osm_file.pbf` (unless you named the pbf file `your_osm.pbf`..). so your graph is already built in `./graphs`? how do you call docker-compose exactly?

**Comment by nilsnolde** [comment]
ORS logs look fine on first glance. Could be a number of things you’re not doing right and checking all of them would take more time than I’m willing to invest tbh. I didn’t try this image in a longer time, and with ORS not in ages. It might well be that the ORS team changed some stuff that invalidates the docker-compose.yml we have in this repo. 

Maybe I’ll try myself next week if I remember. Even though you didn’t seem to learn much and still write crap like „reply as soon as possible“. Fair warning: next time you write smth like that, I’ll block you from all repos I maintain. Please learn how to ask for **unpaid** help.
