### ISSUE TITLE
docker-entrypoint.sh needs to exec npm

### ISSUE THREAD

**Issue by andrewchernow** [VROOM-Project/vroom-docker#58]
the entry point script is not exec'n npm start. This means it creates a sub shell and does not receive SIGINT, SIGTERM, etc. from docker daemon: like a CTRL+C. The docker daemon will wait 10 seconds (default timeout) before force downing a container.  The result is, a 10s hang whenever vroom container is stopped. The below should fix the issue. 
```bash
cd /vroom-express 
exec VROOM_ROUTER=${VROOM_ROUTER} VROOM_LOG=${VROOM_LOG} npm start
```

**Comment by nilsnolde** [comment]
aah, I never really questioned that behavior and figured it's some sort of http server draining period that gets triggered. I see it happening in many images and their common denominator was exposing a http server. your explanation makes more sense though, thanks for that, I'll add it.

**Comment by nilsnolde** [comment]
jep that definitely worked! just pushed it. thanks again
