### ISSUE TITLE
Ditch Dockerhub for GitHub registry

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom-docker#68]
So Dockerhub chose to take the Travis CI route to give up on hosting images for free and push eligible orgs to their “OSS program”. Having the Travis experience, I’d rather go for GitHub right away. 

Since we don’t have a “latest” image, there’s no action to take. Old images will continue to be hosted on Dockerhub, but future images will be published on GitHub packages, it’s pretty seamless, I already did that for most of our images.

**Comment by jcoupey** [comment]
Sounds good and straightforward.

**Comment by nilsnolde** [comment]
Well, they had the decency to take it back after a huge shit storm. Still, we can push to both registries, so we're prepared for the inevitable.
