### ISSUE TITLE
Publish latest image

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom-docker#72]
I'd publish a latest image on a schedule, e.g. once a week, same as I do for Valhalla image. And the best that can be done considering this project is out-of-source. I'll add a clear description when exactly it's built (Sunday) and people will have to check upstream master commits against image build dates, for super bleeding edge.

**Comment by elkashefehab** [comment]
thank you, so when should I expect this version to be released? max_distance feature one of most important feature I have waited for

**Comment by nilsnolde** [comment]
Feel free to do the changes yourself, it's open source :) Otherwise it might take a bit.

**Comment by jcoupey** [comment]
I just pushed a release candidate for the next version, so building the `v1.14.0-rc.1` tag with the usual workflow whenever possible would do the trick short-term.

On a longer-term consideration, I'm not sure publishing weekly images is really worth the trouble. The upstream dev happens in spikes with some busy periods. But most weeks in the year pass by without a merge to master...

**Comment by nilsnolde** [comment]
True. On the other hand it'd also remove the need to version this project at all and strictly stick to upstream, eg when updating the base image or so, when things are severely deprecated (eg we're still using   node 12, that's ancient). I'm personally a big opponent of wasting CI hours, but we're talking < 10 hours on the whole year:) 

Once I'd ever test docker artifact caching in CI, a single run would take not even 1 min if nothing changed upstream. But that'd be for next year:)
